export let brands = [
    {id:0, name:'AUDI', checked:false, count:4},
    {id:1, name:'BMW', checked:false, count:7},
    {id:2, name:'FERRARI', checked:false, count:4},
    {id:3, name:'FIAT', checked:false, count:5},
    {id:4, name:'MASERATI', checked:false, count:5}
]

export let types = [
    {id:0, name:'Berlina', checked:false, count:9},
    {id:1, name:'CityCar', checked:false, count:2},
    {id:2, name:'Jeep', checked:false, count:5},
    {id:3, name:'Sportiva', checked:false, count:8},
    {id:4, name:'SUV', checked:false, count:1}
]

export var cars = [
    {
        "id": 0,
        "brand": "MASERATI",
        "model": "Ghibli",
        "type": "Sportiva",
        "price": 71000,
        "discount": 10,
        "image1": "maserati_ghibli_img1.jpg",
        "image2": "maserati_ghibli_img2.jpg",
        "image3": "maserati_ghibli_img3.jpg",
        "userId": 1,
        "username": "JoeVan"
    },
    {
        "id": 1,
        "brand": "BMW",
        "model": "Serie 1",
        "type": "Berlina",
        "price": 27000,
        "discount": 4,
        "image1": "bmw_serie1_img1.jpg",
        "image2": "bmw_serie1_img2.jpg",
        "image3": "bmw_serie1_img3.jpg",
        "userId": 0,
        "username": "StanfRei"
    },
    {
        "id": 2,
        "brand": "FERRARI",
        "model": "F40",
        "type": "Sportiva",
        "price": 900000,
        "discount": 13,
        "image1": "ferrari_f40_img1.jpg",
        "image2": "ferrari_f40_img2.jpg",
        "image3": "ferrari_f40_img3.jpg",
        "userId": 1,
        "username": "JoeVan"
    },
    {
        "id": 3,
        "brand": "FERRARI",
        "model": "Portofino",
        "type": "Sportiva",
        "price": 195000,
        "discount": 14,
        "image1": "ferrari_portofino_img1.jpg",
        "image2": "ferrari_portofino_img2.jpg",
        "image3": "ferrari_portofino_img3.jpg",
        "userId": 2,
        "username": "AmparLed"
    },
    {
        "id": 4,
        "brand": "AUDI",
        "model": "Q7",
        "type": "Jeep",
        "price": 70000,
        "discount": 14,
        "image1": "audi_Q7_img1.jpg",
        "image2": "audi_Q7_img2.jpg",
        "image3": "audi_Q7_img3.jpg",
        "userId": 3,
        "username": "KobyNik"
    },
    {
        "id": 5,
        "brand": "FERRARI",
        "model": "Portofino",
        "type": "Sportiva",
        "price": 195000,
        "discount": 0,
        "image1": "ferrari_portofino_img1.jpg",
        "image2": "ferrari_portofino_img2.jpg",
        "image3": "ferrari_portofino_img3.jpg",
        "userId": 2,
        "username": "AmparLed"
    },
    {
        "id": 6,
        "brand": "FIAT",
        "model": "500 X Lounge",
        "type": "Berlina",
        "price": 21600,
        "discount": 0,
        "image1": "fiat_500XLounge_img1.jpg",
        "image2": "fiat_500XLounge_img2.jpg",
        "image3": "fiat_500XLounge_img3.jpg",
        "userId": 3,
        "username": "KobyNik"
    },
    {
        "id": 7,
        "brand": "BMW",
        "model": "X5",
        "type": "Jeep",
        "price": 67000,
        "discount": 18,
        "image1": "bmw_x5_img1.jpg",
        "image2": "bmw_x5_img2.jpg",
        "image3": "bmw_x5_img3.jpg",
        "userId": 3,
        "username": "KobyNik"
    },
    {
        "id": 8,
        "brand": "BMW",
        "model": "X5",
        "type": "Jeep",
        "price": 67000,
        "discount": 16,
        "image1": "bmw_x5_img1.jpg",
        "image2": "bmw_x5_img2.jpg",
        "image3": "bmw_x5_img3.jpg",
        "userId": 4,
        "username": "KiaraMur"
    },
    {
        "id": 9,
        "brand": "AUDI",
        "model": "A1",
        "type": "Berlina",
        "price": 22000,
        "discount": 7,
        "image1": "audi_A1_img1.jpg",
        "image2": "audi_A1_img2.jpg",
        "image3": "audi_A1_img3.jpg",
        "userId": 2,
        "username": "AmparLed"
    },
    {
        "id": 10,
        "brand": "FIAT",
        "model": "500",
        "type": "CityCar",
        "price": 10900,
        "discount": 19,
        "image1": "fiat_500_img1.jpg",
        "image2": "fiat_500_img2.jpg",
        "image3": "fiat_500_img3.jpg",
        "userId": 1,
        "username": "JoeVan"
    },
    {
        "id": 11,
        "brand": "AUDI",
        "model": "A1",
        "type": "Berlina",
        "price": 22000,
        "discount": 15,
        "image1": "audi_A1_img1.jpg",
        "image2": "audi_A1_img2.jpg",
        "image3": "audi_A1_img3.jpg",
        "userId": 1,
        "username": "JoeVan"
    },
    {
        "id": 12,
        "brand": "FIAT",
        "model": "500",
        "type": "CityCar",
        "price": 10900,
        "discount": 10,
        "image1": "fiat_500_img1.jpg",
        "image2": "fiat_500_img2.jpg",
        "image3": "fiat_500_img3.jpg",
        "userId": 1,
        "username": "JoeVan"
    },
    {
        "id": 13,
        "brand": "FERRARI",
        "model": "Portofino",
        "type": "Sportiva",
        "price": 195000,
        "discount": 3,
        "image1": "ferrari_portofino_img1.jpg",
        "image2": "ferrari_portofino_img2.jpg",
        "image3": "ferrari_portofino_img3.jpg",
        "userId": 4,
        "username": "KiaraMur"
    },
    {
        "id": 14,
        "brand": "FIAT",
        "model": "500 X Lounge",
        "type": "Berlina",
        "price": 21600,
        "discount": 4,
        "image1": "fiat_500XLounge_img1.jpg",
        "image2": "fiat_500XLounge_img2.jpg",
        "image3": "fiat_500XLounge_img3.jpg",
        "userId": 4,
        "username": "KiaraMur"
    },
    {
        "id": 15,
        "brand": "BMW",
        "model": "X5",
        "type": "Jeep",
        "price": 67000,
        "discount": 11,
        "image1": "bmw_x5_img1.jpg",
        "image2": "bmw_x5_img2.jpg",
        "image3": "bmw_x5_img3.jpg",
        "userId": 4,
        "username": "KiaraMur"
    },
    {
        "id": 19,
        "brand": "BMW",
        "model": "X5",
        "type": "Jeep",
        "price": 67000,
        "discount": 14,
        "image1": "bmw_x5_img1.jpg",
        "image2": "bmw_x5_img2.jpg",
        "image3": "bmw_x5_img3.jpg",
        "userId": 2,
        "username": "AmparLed"
    },
    {
        "id": 20,
        "brand": "MASERATI",
        "model": "Ghibli",
        "type": "Sportiva",
        "price": 71000,
        "discount": 13,
        "image1": "maserati_ghibli_img1.jpg",
        "image2": "maserati_ghibli_img2.jpg",
        "image3": "maserati_ghibli_img3.jpg",
        "userId": 0,
        "username": "StanfRei"
    },
    {
        "id": 21,
        "brand": "MASERATI",
        "model": "MC 20",
        "type": "Sportiva",
        "price": 200000,
        "discount": 13,
        "image1": "maserati_mc20_img1.jpg",
        "image2": "maserati_mc20_img2.jpg",
        "image3": "maserati_mc20_img3.jpg",
        "userId": 3,
        "username": "KobyNik"
    },
    {
        "id": 23,
        "brand": "AUDI",
        "model": "A1",
        "type": "Berlina",
        "price": 22000,
        "discount": 3,
        "image1": "audi_A1_img1.jpg",
        "image2": "audi_A1_img2.jpg",
        "image3": "audi_A1_img3.jpg",
        "userId": 2,
        "username": "AmparLed"
    },
    {
        "id": 24,
        "brand": "MASERATI",
        "model": "MC 20",
        "type": "Sportiva",
        "price": 200000,
        "discount": 3,
        "image1": "maserati_mc20_img1.jpg",
        "image2": "maserati_mc20_img2.jpg",
        "image3": "maserati_mc20_img3.jpg",
        "userId": 0,
        "username": "StanfRei"
    },
    {
        "id": 25,
        "brand": "FIAT",
        "model": "500 X Lounge",
        "type": "Berlina",
        "price": 21600,
        "discount": 15,
        "image1": "fiat_500_img1.jpg",
        "image2": "fiat_500_img2.jpg",
        "image3": "fiat_500_img3.jpg",
        "userId": 3,
        "username": "KobyNik"
    },
    {
        "id": 26,
        "brand": "BMW",
        "model": "Serie 1",
        "type": "Berlina",
        "price": 27000,
        "discount": 10,
        "image1": "bmw_serie1_img1.jpg",
        "image2": "bmw_serie1_img2.jpg",
        "image3": "bmw_serie1_img3.jpg",
        "userId": 0,
        "username": "StanfRei"
    },
    {
        "id": 27,
        "brand": "MASERATI",
        "model": "Levante",
        "type": "SUV",
        "price": 75900,
        "discount": 4,
        "image1": "maserati_levante_img1.jpg",
        "image2": "maserati_levante_img2.jpg",
        "image3": "maserati_levante_img3.jpg",
        "userId": 4,
        "username": "KiaraMur"
    },
    {
        "id": 28,
        "brand": "BMW",
        "model": "Serie 1",
        "type": "Berlina",
        "price": 27000,
        "discount": 8,
        "image1": "bmw_serie1_img1.jpg",
        "image2": "bmw_serie1_img2.jpg",
        "image3": "bmw_serie1_img3.jpg",
        "userId": 0,
        "username": "StanfRei"
    }
]

export var ratings = [
      {
        "rating": 3
      },
      {
        "rating": 1
      },
      {
        "rating": 3
      },
      {
        "rating": 3
      },
      {
        "rating": 3
      },
      {
        "rating": 5
      },
      {
        "rating": 3
      },
      {
        "rating": 5
      },
      {
        "rating": 1
      },
      {
        "rating": 4
      },
      {
        "rating": 5
      },
      {
        "rating": 1
      },
      {
        "rating": 2
      },
      {
        "rating": 4
      },
      {
        "rating": 1
      },
      {
        "rating": 2
      },
      {
        "rating": 2
      },
      {
        "rating": 2
      },
      {
        "rating": 1
      },
      {
        "rating": 5
      }
    ]
    
export var users = [
    {
        "id": 0,
        "firstName": "Stanford",
        "lastName": "Reilly",
        "username": "StanfRei",
        "password": "StanfRei",
        "email": "StanfRei@.email.com",
        
    },
    {
        "id": 1,
        "firstName": "Joe",
        "lastName": "Vandervort",
        "username": "JoeVan",
        "password": "JoeVan",
        "email": "JoeVan@.email.com",
        
    },
    {
        "id": 2,
        "firstName": "Amparo",
        "lastName": "Ledner",
        "username": "AmparLed",
        "password": "AmparLed",
        "email": "AmparLed@.email.com",
       
    },
    {
        "id": 3,
        "firstName": "Koby",
        "lastName": "Nikolaus",
        "username": "KobyNik",
        "password": "KobyNik",
        "email": "KobyNik@.email.com",
        
    },
    {
        "id": 4,
        "firstName": "Kiara",
        "lastName": "Murray",
        "username": "KiaraMur",
        "password": "KiaraMur",
        "email": "KiaraMur@.email.com",
       
    }
]

export var usersAndMore = [
    {
        "id": 0,
        "firstName": "Stanford",
        "lastName": "Reilly",
        "username": "StanfRei",
        "password": "StanfRei",
        "email": "StanfRei@.email.com",
        "cars": [
            {
                "id": 24,
                "brand": "MASERATI",
                "model": "MC 20",
                "type": "Sportiva",
                "price": 200000,
                "discount": 3,
                "image1": "maserati_mc20_img1.jpg",
                "image2": "maserati_mc20_img2.jpg",
                "image3": "maserati_mc20_img3.jpg",
                "userId": 0,
                "username": "StanfRei"
            },
            {
                "id": 28,
                "brand": "BMW",
                "model": "Serie 1",
                "type": "Berlina",
                "price": 27000,
                "discount": 8,
                "image1": "bmw_serie1_img1.jpg",
                "image2": "bmw_serie1_img2.jpg",
                "image3": "bmw_serie1_img3.jpg",
                "userId": 0,
                "username": "StanfRei"
            },
            {
                "id": 1,
                "brand": "BMW",
                "model": "Serie 1",
                "type": "Berlina",
                "price": 27000,
                "discount": 4,
                "image1": "bmw_serie1_img1.jpg",
                "image2": "bmw_serie1_img2.jpg",
                "image3": "bmw_serie1_img3.jpg",
                "userId": 0,
                "username": "StanfRei"
            },
            {
                "id": 20,
                "brand": "MASERATI",
                "model": "Ghibli",
                "type": "Sportiva",
                "price": 71000,
                "discount": 13,
                "image1": "maserati_ghibli_img1.jpg",
                "image2": "maserati_ghibli_img2.jpg",
                "image3": "maserati_ghibli_img3.jpg",
                "userId": 0,
                "username": "StanfRei"
            },
            {
                "id": 26,
                "brand": "BMW",
                "model": "Serie 1",
                "type": "Berlina",
                "price": 27000,
                "discount": 10,
                "image1": "bmw_serie1_img1.jpg",
                "image2": "bmw_serie1_img2.jpg",
                "image3": "bmw_serie1_img3.jpg",
                "userId": 0,
                "username": "StanfRei"
            }
        ],
        "recentSeenCars": [
            {
                "id": 13,
                "brand": "FERRARI",
                "model": "Portofino",
                "type": "Sportiva",
                "price": 195000,
                "discount": 3,
                "image1": "ferrari_portofino_img1.jpg",
                "image2": "ferrari_portofino_img2.jpg",
                "image3": "ferrari_portofino_img3.jpg",
                "userId": 4,
                "username": "KiaraMur"
            },
            {
                "id": 2,
                "brand": "FERRARI",
                "model": "F40",
                "type": "Sportiva",
                "price": 900000,
                "discount": 13,
                "image1": "ferrari_f40_img1.jpg",
                "image2": "ferrari_f40_img2.jpg",
                "image3": "ferrari_f40_img3.jpg",
                "userId": 1,
                "username": "JoeVan"
            },
            {
                "id": 2,
                "brand": "FERRARI",
                "model": "F40",
                "type": "Sportiva",
                "price": 900000,
                "discount": 13,
                "image1": "ferrari_f40_img1.jpg",
                "image2": "ferrari_f40_img2.jpg",
                "image3": "ferrari_f40_img3.jpg",
                "userId": 1,
                "username": "JoeVan"
            },
            {
                "id": 1,
                "brand": "BMW",
                "model": "Serie 1",
                "type": "Berlina",
                "price": 27000,
                "discount": 4,
                "image1": "bmw_serie1_img1.jpg",
                "image2": "bmw_serie1_img2.jpg",
                "image3": "bmw_serie1_img3.jpg",
                "userId": 0,
                "username": "StanfRei"
            },
            {
                "id": 23,
                "brand": "AUDI",
                "model": "A1",
                "type": "Berlina",
                "price": 22000,
                "discount": 3,
                "image1": "audi_A1_img1.jpg",
                "image2": "audi_A1_img2.jpg",
                "image3": "audi_A1_img3.jpg",
                "userId": 2,
                "username": "AmparLed"
            }
        ],
        "observedCars": [
            {
                "id": 1,
                "brand": "BMW",
                "model": "Serie 1",
                "type": "Berlina",
                "price": 27000,
                "discount": 4,
                "image1": "bmw_serie1_img1.jpg",
                "image2": "bmw_serie1_img2.jpg",
                "image3": "bmw_serie1_img3.jpg",
                "userId": 0,
                "username": "StanfRei",
                "observedByUsername": "StanfRei",
                "observedByUserId": 0
            },
            {
                "id": 4,
                "brand": "AUDI",
                "model": "Q7",
                "type": "Jeep",
                "price": 70000,
                "discount": 14,
                "image1": "audi_Q7_img1.jpg",
                "image2": "audi_Q7_img2.jpg",
                "image3": "audi_Q7_img3.jpg",
                "userId": 3,
                "username": "KobyNik",
                "observedByUsername": "StanfRei",
                "observedByUserId": 0
            },
            {
                "id": 9,
                "brand": "AUDI",
                "model": "A1",
                "type": "Berlina",
                "price": 22000,
                "discount": 7,
                "image1": "audi_A1_img1.jpg",
                "image2": "audi_A1_img2.jpg",
                "image3": "audi_A1_img3.jpg",
                "userId": 2,
                "username": "AmparLed",
                "observedByUsername": "StanfRei",
                "observedByUserId": 0
            }
        ],
        "ratings": [
            3,
            5,
            3,
            2,
            1,
            3,
            5,
            5,
            5,
            2,
            5,
            1
        ]
    },
    {
        "id": 1,
        "firstName": "Joe",
        "lastName": "Vandervort",
        "username": "JoeVan",
        "password": "JoeVan",
        "email": "JoeVan@.email.com",
        "cars": [
            {
                "id": 10,
                "brand": "FIAT",
                "model": "500",
                "type": "CityCar",
                "price": 10900,
                "discount": 19,
                "image1": "fiat_500_img1.jpg",
                "image2": "fiat_500_img2.jpg",
                "image3": "fiat_500_img3.jpg",
                "userId": 1,
                "username": "JoeVan"
            },
            {
                "id": 0,
                "brand": "MASERATI",
                "model": "Ghibli",
                "type": "Sportiva",
                "price": 71000,
                "discount": 10,
                "image1": "maserati_ghibli_img1.jpg",
                "image2": "maserati_ghibli_img2.jpg",
                "image3": "maserati_ghibli_img3.jpg",
                "userId": 1,
                "username": "JoeVan"
            },
            {
                "id": 2,
                "brand": "FERRARI",
                "model": "F40",
                "type": "Sportiva",
                "price": 900000,
                "discount": 13,
                "image1": "ferrari_f40_img1.jpg",
                "image2": "ferrari_f40_img2.jpg",
                "image3": "ferrari_f40_img3.jpg",
                "userId": 1,
                "username": "JoeVan"
            },
            {
                "id": 11,
                "brand": "AUDI",
                "model": "A1",
                "type": "Berlina",
                "price": 22000,
                "discount": 15,
                "image1": "audi_A1_img1.jpg",
                "image2": "audi_A1_img2.jpg",
                "image3": "audi_A1_img3.jpg",
                "userId": 1,
                "username": "JoeVan"
            },
            {
                "id": 12,
                "brand": "FIAT",
                "model": "500",
                "type": "CityCar",
                "price": 10900,
                "discount": 10,
                "image1": "fiat_500_img1.jpg",
                "image2": "fiat_500_img2.jpg",
                "image3": "fiat_500_img3.jpg",
                "userId": 1,
                "username": "JoeVan"
            }
        ],
        "recentSeenCars": [
            {
                "id": 24,
                "brand": "MASERATI",
                "model": "MC 20",
                "type": "Sportiva",
                "price": 200000,
                "discount": 3,
                "image1": "maserati_mc20_img1.jpg",
                "image2": "maserati_mc20_img2.jpg",
                "image3": "maserati_mc20_img3.jpg",
                "userId": 0,
                "username": "StanfRei"
            },
            {
                "id": 2,
                "brand": "FERRARI",
                "model": "F40",
                "type": "Sportiva",
                "price": 900000,
                "discount": 13,
                "image1": "ferrari_f40_img1.jpg",
                "image2": "ferrari_f40_img2.jpg",
                "image3": "ferrari_f40_img3.jpg",
                "userId": 1,
                "username": "JoeVan"
            },
            {
                "id": 12,
                "brand": "FIAT",
                "model": "500",
                "type": "CityCar",
                "price": 10900,
                "discount": 10,
                "image1": "fiat_500_img1.jpg",
                "image2": "fiat_500_img2.jpg",
                "image3": "fiat_500_img3.jpg",
                "userId": 1,
                "username": "JoeVan"
            },
            {
                "id": 5,
                "brand": "FERRARI",
                "model": "Portofino",
                "type": "Sportiva",
                "price": 195000,
                "discount": 0,
                "image1": "ferrari_portofino_img1.jpg",
                "image2": "ferrari_portofino_img2.jpg",
                "image3": "ferrari_portofino_img3.jpg",
                "userId": 2,
                "username": "AmparLed"
            },
            {
                "id": 7,
                "brand": "BMW",
                "model": "X5",
                "type": "Jeep",
                "price": 67000,
                "discount": 18,
                "image1": "bmw_x5_img1.jpg",
                "image2": "bmw_x5_img2.jpg",
                "image3": "bmw_x5_img3.jpg",
                "userId": 3,
                "username": "KobyNik"
            }
        ],
        "observedCars": [
            {
                "id": 23,
                "brand": "AUDI",
                "model": "A1",
                "type": "Berlina",
                "price": 22000,
                "discount": 3,
                "image1": "audi_A1_img1.jpg",
                "image2": "audi_A1_img2.jpg",
                "image3": "audi_A1_img3.jpg",
                "userId": 2,
                "username": "AmparLed",
                "observedByUsername": "JoeVan",
                "observedByUserId": 1
            },
            {
                "id": 13,
                "brand": "FERRARI",
                "model": "Portofino",
                "type": "Sportiva",
                "price": 195000,
                "discount": 3,
                "image1": "ferrari_portofino_img1.jpg",
                "image2": "ferrari_portofino_img2.jpg",
                "image3": "ferrari_portofino_img3.jpg",
                "userId": 4,
                "username": "KiaraMur",
                "observedByUsername": "JoeVan",
                "observedByUserId": 1
            },
            {
                "id": 20,
                "brand": "MASERATI",
                "model": "Ghibli",
                "type": "Sportiva",
                "price": 71000,
                "discount": 13,
                "image1": "maserati_ghibli_img1.jpg",
                "image2": "maserati_ghibli_img2.jpg",
                "image3": "maserati_ghibli_img3.jpg",
                "userId": 0,
                "username": "StanfRei",
                "observedByUsername": "JoeVan",
                "observedByUserId": 1
            },
            {
                "id": 4,
                "brand": "AUDI",
                "model": "Q7",
                "type": "Jeep",
                "price": 70000,
                "discount": 14,
                "image1": "audi_Q7_img1.jpg",
                "image2": "audi_Q7_img2.jpg",
                "image3": "audi_Q7_img3.jpg",
                "userId": 3,
                "username": "KobyNik",
                "observedByUsername": "JoeVan",
                "observedByUserId": 1
            },
            {
                "id": 28,
                "brand": "BMW",
                "model": "Serie 1",
                "type": "Berlina",
                "price": 27000,
                "discount": 8,
                "image1": "bmw_serie1_img1.jpg",
                "image2": "bmw_serie1_img2.jpg",
                "image3": "bmw_serie1_img3.jpg",
                "userId": 0,
                "username": "StanfRei",
                "observedByUsername": "JoeVan",
                "observedByUserId": 1
            },
            {
                "id": 14,
                "brand": "FIAT",
                "model": "500 X Lounge",
                "type": "Berlina",
                "price": 21600,
                "discount": 4,
                "image1": "fiat_500XLounge_img1.jpg",
                "image2": "fiat_500XLounge_img2.jpg",
                "image3": "fiat_500XLounge_img3.jpg",
                "userId": 4,
                "username": "KiaraMur",
                "observedByUsername": "JoeVan",
                "observedByUserId": 1
            }
        ],
        "ratings": [
            1,
            5,
            2,
            4,
            1,
            5,
            3,
            1,
            2,
            5,
            2,
            5,
            3,
            1,
            3,
            3,
            3,
            4,
            4
        ]
    },
    {
        "id": 2,
        "firstName": "Amparo",
        "lastName": "Ledner",
        "username": "AmparLed",
        "password": "AmparLed",
        "email": "AmparLed@.email.com",
        "cars": [
            {
                "id": 9,
                "brand": "AUDI",
                "model": "A1",
                "type": "Berlina",
                "price": 22000,
                "discount": 7,
                "image1": "audi_A1_img1.jpg",
                "image2": "audi_A1_img2.jpg",
                "image3": "audi_A1_img3.jpg",
                "userId": 2,
                "username": "AmparLed"
            },
            {
                "id": 5,
                "brand": "FERRARI",
                "model": "Portofino",
                "type": "Sportiva",
                "price": 195000,
                "discount": 0,
                "image1": "ferrari_portofino_img1.jpg",
                "image2": "ferrari_portofino_img2.jpg",
                "image3": "ferrari_portofino_img3.jpg",
                "userId": 2,
                "username": "AmparLed"
            },
            {
                "id": 19,
                "brand": "BMW",
                "model": "X5",
                "type": "Jeep",
                "price": 67000,
                "discount": 14,
                "image1": "bmw_x5_img1.jpg",
                "image2": "bmw_x5_img2.jpg",
                "image3": "bmw_x5_img3.jpg",
                "userId": 2,
                "username": "AmparLed"
            },
            {
                "id": 3,
                "brand": "FERRARI",
                "model": "Portofino",
                "type": "Sportiva",
                "price": 195000,
                "discount": 14,
                "image1": "ferrari_portofino_img1.jpg",
                "image2": "ferrari_portofino_img2.jpg",
                "image3": "ferrari_portofino_img3.jpg",
                "userId": 2,
                "username": "AmparLed"
            },
            {
                "id": 23,
                "brand": "AUDI",
                "model": "A1",
                "type": "Berlina",
                "price": 22000,
                "discount": 3,
                "image1": "audi_A1_img1.jpg",
                "image2": "audi_A1_img2.jpg",
                "image3": "audi_A1_img3.jpg",
                "userId": 2,
                "username": "AmparLed"
            }
        ],
        "recentSeenCars": [
            {
                "id": 25,
                "brand": "FIAT",
                "model": "500 X Lounge",
                "type": "Berlina",
                "price": 21600,
                "discount": 15,
                "image1": "fiat_500XLounge_img1.jpg",
                "image2": "fiat_500XLounge_img2.jpg",
                "image3": "fiat_500XLounge_img3.jpg",
                "userId": 3,
                "username": "KobyNik"
            },
            {
                "id": 27,
                "brand": "MASERATI",
                "model": "Levante",
                "type": "SUV",
                "price": 75900,
                "discount": 4,
                "image1": "maserati_levante_img1.jpg",
                "image2": "maserati_levante_img2.jpg",
                "image3": "maserati_levante_img3.jpg",
                "userId": 4,
                "username": "KiaraMur"
            },
            {
                "id": 2,
                "brand": "FERRARI",
                "model": "F40",
                "type": "Sportiva",
                "price": 900000,
                "discount": 13,
                "image1": "ferrari_f40_img1.jpg",
                "image2": "ferrari_f40_img2.jpg",
                "image3": "ferrari_f40_img3.jpg",
                "userId": 1,
                "username": "JoeVan"
            },
            {
                "id": 23,
                "brand": "AUDI",
                "model": "A1",
                "type": "Berlina",
                "price": 22000,
                "discount": 3,
                "image1": "audi_A1_img1.jpg",
                "image2": "audi_A1_img2.jpg",
                "image3": "audi_A1_img3.jpg",
                "userId": 2,
                "username": "AmparLed"
            },
            {
                "id": 12,
                "brand": "FIAT",
                "model": "500",
                "type": "CityCar",
                "price": 10900,
                "discount": 10,
                "image1": "fiat_500_img1.jpg",
                "image2": "fiat_500_img2.jpg",
                "image3": "fiat_500_img3.jpg",
                "userId": 1,
                "username": "JoeVan"
            },
            {
                "id": 23,
                "brand": "AUDI",
                "model": "A1",
                "type": "Berlina",
                "price": 22000,
                "discount": 3,
                "image1": "audi_A1_img1.jpg",
                "image2": "audi_A1_img2.jpg",
                "image3": "audi_A1_img3.jpg",
                "userId": 2,
                "username": "AmparLed"
            },
            {
                "id": 2,
                "brand": "FERRARI",
                "model": "F40",
                "type": "Sportiva",
                "price": 900000,
                "discount": 13,
                "image1": "ferrari_f40_img1.jpg",
                "image2": "ferrari_f40_img2.jpg",
                "image3": "ferrari_f40_img3.jpg",
                "userId": 1,
                "username": "JoeVan"
            },
            {
                "id": 13,
                "brand": "FERRARI",
                "model": "Portofino",
                "type": "Sportiva",
                "price": 195000,
                "discount": 3,
                "image1": "ferrari_portofino_img1.jpg",
                "image2": "ferrari_portofino_img2.jpg",
                "image3": "ferrari_portofino_img3.jpg",
                "userId": 4,
                "username": "KiaraMur"
            },
            {
                "id": 26,
                "brand": "BMW",
                "model": "Serie 1",
                "type": "Berlina",
                "price": 27000,
                "discount": 10,
                "image1": "bmw_serie1_img1.jpg",
                "image2": "bmw_serie1_img2.jpg",
                "image3": "bmw_serie1_img3.jpg",
                "userId": 0,
                "username": "StanfRei"
            }
        ],
        "observedCars": [
            {
                "id": 12,
                "brand": "FIAT",
                "model": "500",
                "type": "CityCar",
                "price": 10900,
                "discount": 10,
                "image1": "fiat_500_img1.jpg",
                "image2": "fiat_500_img2.jpg",
                "image3": "fiat_500_img3.jpg",
                "userId": 1,
                "username": "JoeVan",
                "observedByUsername": "AmparLed",
                "observedByUserId": 2
            }
        ],
        "ratings": [
            2,
            2,
            3,
            3,
            1,
            1,
            1,
            4,
            4,
            4
        ]
    },
    {
        "id": 3,
        "firstName": "Koby",
        "lastName": "Nikolaus",
        "username": "KobyNik",
        "password": "KobyNik",
        "email": "KobyNik@.email.com",
        "cars": [
            {
                "id": 6,
                "brand": "FIAT",
                "model": "500 X Lounge",
                "type": "Berlina",
                "price": 21600,
                "discount": 0,
                "image1": "fiat_500XLounge_img1.jpg",
                "image2": "fiat_500XLounge_img2.jpg",
                "image3": "fiat_500XLounge_img3.jpg",
                "userId": 3,
                "username": "KobyNik"
            },
            {
                "id": 4,
                "brand": "AUDI",
                "model": "Q7",
                "type": "Jeep",
                "price": 70000,
                "discount": 14,
                "image1": "audi_Q7_img1.jpg",
                "image2": "audi_Q7_img2.jpg",
                "image3": "audi_Q7_img3.jpg",
                "userId": 3,
                "username": "KobyNik"
            },
            {
                "id": 25,
                "brand": "FIAT",
                "model": "500 X Lounge",
                "type": "Berlina",
                "price": 21600,
                "discount": 15,
                "image1": "fiat_500XLounge_img1.jpg",
                "image2": "fiat_500XLounge_img2.jpg",
                "image3": "fiat_500XLounge_img3.jpg",
                "userId": 3,
                "username": "KobyNik"
            },
            {
                "id": 7,
                "brand": "BMW",
                "model": "X5",
                "type": "Jeep",
                "price": 67000,
                "discount": 18,
                "image1": "bmw_x5_img1.jpg",
                "image2": "bmw_x5_img2.jpg",
                "image3": "bmw_x5_img3.jpg",
                "userId": 3,
                "username": "KobyNik"
            },
            {
                "id": 21,
                "brand": "MASERATI",
                "model": "MC 20",
                "type": "Sportiva",
                "price": 200000,
                "discount": 13,
                "image1": "maserati_mc20_img1.jpg",
                "image2": "maserati_mc20_img2.jpg",
                "image3": "maserati_mc20_img3.jpg",
                "userId": 3,
                "username": "KobyNik"
            }
        ],
        "recentSeenCars": [
            {
                "id": 3,
                "brand": "FERRARI",
                "model": "Portofino",
                "type": "Sportiva",
                "price": 195000,
                "discount": 14,
                "image1": "ferrari_portofino_img1.jpg",
                "image2": "ferrari_portofino_img2.jpg",
                "image3": "ferrari_portofino_img3.jpg",
                "userId": 2,
                "username": "AmparLed"
            },
            {
                "id": 25,
                "brand": "FIAT",
                "model": "500 X Lounge",
                "type": "Berlina",
                "price": 21600,
                "discount": 15,
                "image1": "fiat_500XLounge_img1.jpg",
                "image2": "fiat_500XLounge_img2.jpg",
                "image3": "fiat_500XLounge_img3.jpg",
                "userId": 3,
                "username": "KobyNik"
            },
            {
                "id": 15,
                "brand": "BMW",
                "model": "X5",
                "type": "Jeep",
                "price": 67000,
                "discount": 11,
                "image1": "bmw_x5_img1.jpg",
                "image2": "bmw_x5_img2.jpg",
                "image3": "bmw_x5_img3.jpg",
                "userId": 4,
                "username": "KiaraMur"
            },
            {
                "id": 24,
                "brand": "MASERATI",
                "model": "MC 20",
                "type": "Sportiva",
                "price": 200000,
                "discount": 3,
                "image1": "maserati_mc20_img1.jpg",
                "image2": "maserati_mc20_img2.jpg",
                "image3": "maserati_mc20_img3.jpg",
                "userId": 0,
                "username": "StanfRei"
            },
            {
                "id": 21,
                "brand": "MASERATI",
                "model": "MC 20",
                "type": "Sportiva",
                "price": 200000,
                "discount": 13,
                "image1": "maserati_mc20_img1.jpg",
                "image2": "maserati_mc20_img2.jpg",
                "image3": "maserati_mc20_img3.jpg",
                "userId": 3,
                "username": "KobyNik"
            }
        ],
        "observedCars": [
            {
                "id": 26,
                "brand": "BMW",
                "model": "Serie 1",
                "type": "Berlina",
                "price": 27000,
                "discount": 10,
                "image1": "bmw_serie1_img1.jpg",
                "image2": "bmw_serie1_img2.jpg",
                "image3": "bmw_serie1_img3.jpg",
                "userId": 0,
                "username": "StanfRei",
                "observedByUsername": "KobyNik",
                "observedByUserId": 3
            },
            {
                "id": 14,
                "brand": "FIAT",
                "model": "500 X Lounge",
                "type": "Berlina",
                "price": 21600,
                "discount": 4,
                "image1": "fiat_500XLounge_img1.jpg",
                "image2": "fiat_500XLounge_img2.jpg",
                "image3": "fiat_500XLounge_img3.jpg",
                "userId": 4,
                "username": "KiaraMur",
                "observedByUsername": "KobyNik",
                "observedByUserId": 3
            },
            {
                "id": 20,
                "brand": "MASERATI",
                "model": "Ghibli",
                "type": "Sportiva",
                "price": 71000,
                "discount": 13,
                "image1": "maserati_ghibli_img1.jpg",
                "image2": "maserati_ghibli_img2.jpg",
                "image3": "maserati_ghibli_img3.jpg",
                "userId": 0,
                "username": "StanfRei",
                "observedByUsername": "KobyNik",
                "observedByUserId": 3
            },
            {
                "id": 3,
                "brand": "FERRARI",
                "model": "Portofino",
                "type": "Sportiva",
                "price": 195000,
                "discount": 14,
                "image1": "ferrari_portofino_img1.jpg",
                "image2": "ferrari_portofino_img2.jpg",
                "image3": "ferrari_portofino_img3.jpg",
                "userId": 2,
                "username": "AmparLed",
                "observedByUsername": "KobyNik",
                "observedByUserId": 3
            }
        ],
        "ratings": [
            5,
            4,
            5,
            3,
            1,
            3,
            1,
            3,
            4,
            1,
            3,
            1,
            4,
            1
        ]
    },
    {
        "id": 4,
        "firstName": "Kiara",
        "lastName": "Murray",
        "username": "KiaraMur",
        "password": "KiaraMur",
        "email": "KiaraMur@.email.com",
        "cars": [
            {
                "id": 27,
                "brand": "MASERATI",
                "model": "Levante",
                "type": "SUV",
                "price": 75900,
                "discount": 4,
                "image1": "maserati_levante_img1.jpg",
                "image2": "maserati_levante_img2.jpg",
                "image3": "maserati_levante_img3.jpg",
                "userId": 4,
                "username": "KiaraMur"
            },
            {
                "id": 8,
                "brand": "BMW",
                "model": "X5",
                "type": "Jeep",
                "price": 67000,
                "discount": 16,
                "image1": "bmw_x5_img1.jpg",
                "image2": "bmw_x5_img2.jpg",
                "image3": "bmw_x5_img3.jpg",
                "userId": 4,
                "username": "KiaraMur"
            },
            {
                "id": 13,
                "brand": "FERRARI",
                "model": "Portofino",
                "type": "Sportiva",
                "price": 195000,
                "discount": 3,
                "image1": "ferrari_portofino_img1.jpg",
                "image2": "ferrari_portofino_img2.jpg",
                "image3": "ferrari_portofino_img3.jpg",
                "userId": 4,
                "username": "KiaraMur"
            },
            {
                "id": 14,
                "brand": "FIAT",
                "model": "500 X Lounge",
                "type": "Berlina",
                "price": 21600,
                "discount": 4,
                "image1": "fiat_500XLounge_img1.jpg",
                "image2": "fiat_500XLounge_img2.jpg",
                "image3": "fiat_500XLounge_img3.jpg",
                "userId": 4,
                "username": "KiaraMur"
            },
            {
                "id": 15,
                "brand": "BMW",
                "model": "X5",
                "type": "Jeep",
                "price": 67000,
                "discount": 11,
                "image1": "bmw_x5_img1.jpg",
                "image2": "bmw_x5_img2.jpg",
                "image3": "bmw_x5_img3.jpg",
                "userId": 4,
                "username": "KiaraMur"
            }
        ],
        "recentSeenCars": [
            {
                "id": 14,
                "brand": "FIAT",
                "model": "500 X Lounge",
                "type": "Berlina",
                "price": 21600,
                "discount": 4,
                "image1": "fiat_500XLounge_img1.jpg",
                "image2": "fiat_500XLounge_img2.jpg",
                "image3": "fiat_500XLounge_img3.jpg",
                "userId": 4,
                "username": "KiaraMur"
            },
            {
                "id": 15,
                "brand": "BMW",
                "model": "X5",
                "type": "Jeep",
                "price": 67000,
                "discount": 11,
                "image1": "bmw_x5_img1.jpg",
                "image2": "bmw_x5_img2.jpg",
                "image3": "bmw_x5_img3.jpg",
                "userId": 4,
                "username": "KiaraMur"
            },
            {
                "id": 3,
                "brand": "FERRARI",
                "model": "Portofino",
                "type": "Sportiva",
                "price": 195000,
                "discount": 14,
                "image1": "ferrari_portofino_img1.jpg",
                "image2": "ferrari_portofino_img2.jpg",
                "image3": "ferrari_portofino_img3.jpg",
                "userId": 2,
                "username": "AmparLed"
            },
            {
                "id": 14,
                "brand": "FIAT",
                "model": "500 X Lounge",
                "type": "Berlina",
                "price": 21600,
                "discount": 4,
                "image1": "fiat_500XLounge_img1.jpg",
                "image2": "fiat_500XLounge_img2.jpg",
                "image3": "fiat_500XLounge_img3.jpg",
                "userId": 4,
                "username": "KiaraMur"
            },
            {
                "id": 23,
                "brand": "AUDI",
                "model": "A1",
                "type": "Berlina",
                "price": 22000,
                "discount": 3,
                "image1": "audi_A1_img1.jpg",
                "image2": "audi_A1_img2.jpg",
                "image3": "audi_A1_img3.jpg",
                "userId": 2,
                "username": "AmparLed"
            },
            {
                "id": 14,
                "brand": "FIAT",
                "model": "500 X Lounge",
                "type": "Berlina",
                "price": 21600,
                "discount": 4,
                "image1": "fiat_500XLounge_img1.jpg",
                "image2": "fiat_500XLounge_img2.jpg",
                "image3": "fiat_500XLounge_img3.jpg",
                "userId": 4,
                "username": "KiaraMur"
            },
            {
                "id": 20,
                "brand": "MASERATI",
                "model": "Ghibli",
                "type": "Sportiva",
                "price": 71000,
                "discount": 13,
                "image1": "maserati_ghibli_img1.jpg",
                "image2": "maserati_ghibli_img2.jpg",
                "image3": "maserati_ghibli_img3.jpg",
                "userId": 0,
                "username": "StanfRei"
            },
            {
                "id": 19,
                "brand": "BMW",
                "model": "X5",
                "type": "Jeep",
                "price": 67000,
                "discount": 14,
                "image1": "bmw_x5_img1.jpg",
                "image2": "bmw_x5_img2.jpg",
                "image3": "bmw_x5_img3.jpg",
                "userId": 2,
                "username": "AmparLed"
            }
        ],
        "observedCars": [
            {
                "id": 14,
                "brand": "FIAT",
                "model": "500 X Lounge",
                "type": "Berlina",
                "price": 21600,
                "discount": 4,
                "image1": "fiat_500XLounge_img1.jpg",
                "image2": "fiat_500XLounge_img2.jpg",
                "image3": "fiat_500XLounge_img3.jpg",
                "userId": 4,
                "username": "KiaraMur",
                "observedByUsername": "KiaraMur",
                "observedByUserId": 4
            },
            {
                "id": 2,
                "brand": "FERRARI",
                "model": "F40",
                "type": "Sportiva",
                "price": 900000,
                "discount": 13,
                "image1": "ferrari_f40_img1.jpg",
                "image2": "ferrari_f40_img2.jpg",
                "image3": "ferrari_f40_img3.jpg",
                "userId": 1,
                "username": "JoeVan",
                "observedByUsername": "KiaraMur",
                "observedByUserId": 4
            },
            {
                "id": 21,
                "brand": "MASERATI",
                "model": "MC 20",
                "type": "Sportiva",
                "price": 200000,
                "discount": 13,
                "image1": "maserati_mc20_img1.jpg",
                "image2": "maserati_mc20_img2.jpg",
                "image3": "maserati_mc20_img3.jpg",
                "userId": 3,
                "username": "KobyNik",
                "observedByUsername": "KiaraMur",
                "observedByUserId": 4
            },
            {
                "id": 23,
                "brand": "AUDI",
                "model": "A1",
                "type": "Berlina",
                "price": 22000,
                "discount": 3,
                "image1": "audi_A1_img1.jpg",
                "image2": "audi_A1_img2.jpg",
                "image3": "audi_A1_img3.jpg",
                "userId": 2,
                "username": "AmparLed",
                "observedByUsername": "KiaraMur",
                "observedByUserId": 4
            },
            {
                "id": 0,
                "brand": "MASERATI",
                "model": "Ghibli",
                "type": "Sportiva",
                "price": 71000,
                "discount": 10,
                "image1": "maserati_ghibli_img1.jpg",
                "image2": "maserati_ghibli_img2.jpg",
                "image3": "maserati_ghibli_img3.jpg",
                "userId": 1,
                "username": "JoeVan",
                "observedByUsername": "KiaraMur",
                "observedByUserId": 4
            },
            {
                "id": 26,
                "brand": "BMW",
                "model": "Serie 1",
                "type": "Berlina",
                "price": 27000,
                "discount": 10,
                "image1": "bmw_serie1_img1.jpg",
                "image2": "bmw_serie1_img2.jpg",
                "image3": "bmw_serie1_img3.jpg",
                "userId": 0,
                "username": "StanfRei",
                "observedByUsername": "KiaraMur",
                "observedByUserId": 4
            }
        ],
        "ratings": [
            5,
            3,
            2,
            4,
            2,
            2,
            2,
            2,
            3,
            4
        ]
    }
]

export var observedCars = [
    {
        "id": 9,
        "brand": "AUDI",
        "model": "A1",
        "type": "Berlina",
        "price": 22000,
        "discount": 7,
        "image1": "audi_A1_img1.jpg",
        "image2": "audi_A1_img2.jpg",
        "image3": "audi_A1_img3.jpg",
        "userId": 2,
        "username": "AmparLed",
        "observedByUsername": "StanfRei",
        "observedByUserId": 0
    },
    {
        "id": 1,
        "brand": "BMW",
        "model": "Serie 1",
        "type": "Berlina",
        "price": 27000,
        "discount": 4,
        "image1": "bmw_serie1_img1.jpg",
        "image2": "bmw_serie1_img2.jpg",
        "image3": "bmw_serie1_img3.jpg",
        "userId": 0,
        "username": "StanfRei",
        "observedByUsername": "StanfRei",
        "observedByUserId": 0
    },
    {
        "id": 4,
        "brand": "AUDI",
        "model": "Q7",
        "type": "Jeep",
        "price": 70000,
        "discount": 14,
        "image1": "audi_Q7_img1.jpg",
        "image2": "audi_Q7_img2.jpg",
        "image3": "audi_Q7_img3.jpg",
        "userId": 3,
        "username": "KobyNik",
        "observedByUsername": "StanfRei",
        "observedByUserId": 0
    },
    {
        "id": 9,
        "brand": "AUDI",
        "model": "A1",
        "type": "Berlina",
        "price": 22000,
        "discount": 7,
        "image1": "audi_A1_img1.jpg",
        "image2": "audi_A1_img2.jpg",
        "image3": "audi_A1_img3.jpg",
        "userId": 2,
        "username": "AmparLed",
        "observedByUsername": "StanfRei",
        "observedByUserId": 0
    },
    {
        "id": 23,
        "brand": "AUDI",
        "model": "A1",
        "type": "Berlina",
        "price": 22000,
        "discount": 3,
        "image1": "audi_A1_img1.jpg",
        "image2": "audi_A1_img2.jpg",
        "image3": "audi_A1_img3.jpg",
        "userId": 2,
        "username": "AmparLed",
        "observedByUsername": "JoeVan",
        "observedByUserId": 1
    },
    {
        "id": 13,
        "brand": "FERRARI",
        "model": "Portofino",
        "type": "Sportiva",
        "price": 195000,
        "discount": 3,
        "image1": "ferrari_portofino_img1.jpg",
        "image2": "ferrari_portofino_img2.jpg",
        "image3": "ferrari_portofino_img3.jpg",
        "userId": 4,
        "username": "KiaraMur",
        "observedByUsername": "JoeVan",
        "observedByUserId": 1
    },
    {
        "id": 20,
        "brand": "MASERATI",
        "model": "Ghibli",
        "type": "Sportiva",
        "price": 71000,
        "discount": 13,
        "image1": "maserati_ghibli_img1.jpg",
        "image2": "maserati_ghibli_img2.jpg",
        "image3": "maserati_ghibli_img3.jpg",
        "userId": 0,
        "username": "StanfRei",
        "observedByUsername": "JoeVan",
        "observedByUserId": 1
    },
    {
        "id": 4,
        "brand": "AUDI",
        "model": "Q7",
        "type": "Jeep",
        "price": 70000,
        "discount": 14,
        "image1": "audi_Q7_img1.jpg",
        "image2": "audi_Q7_img2.jpg",
        "image3": "audi_Q7_img3.jpg",
        "userId": 3,
        "username": "KobyNik",
        "observedByUsername": "JoeVan",
        "observedByUserId": 1
    },
    {
        "id": 28,
        "brand": "BMW",
        "model": "Serie 1",
        "type": "Berlina",
        "price": 27000,
        "discount": 8,
        "image1": "bmw_serie1_img1.jpg",
        "image2": "bmw_serie1_img2.jpg",
        "image3": "bmw_serie1_img3.jpg",
        "userId": 0,
        "username": "StanfRei",
        "observedByUsername": "JoeVan",
        "observedByUserId": 1
    },
    {
        "id": 14,
        "brand": "FIAT",
        "model": "500 X Lounge",
        "type": "Berlina",
        "price": 21600,
        "discount": 4,
        "image1": "fiat_500XLounge_img1.jpg",
        "image2": "fiat_500XLounge_img2.jpg",
        "image3": "fiat_500XLounge_img3.jpg",
        "userId": 4,
        "username": "KiaraMur",
        "observedByUsername": "JoeVan",
        "observedByUserId": 1
    },
    {
        "id": 12,
        "brand": "FIAT",
        "model": "500",
        "type": "CityCar",
        "price": 10900,
        "discount": 10,
        "image1": "fiat_500_img1.jpg",
        "image2": "fiat_500_img2.jpg",
        "image3": "fiat_500_img3.jpg",
        "userId": 1,
        "username": "JoeVan",
        "observedByUsername": "AmparLed",
        "observedByUserId": 2
    },
    {
        "id": 26,
        "brand": "BMW",
        "model": "Serie 1",
        "type": "Berlina",
        "price": 27000,
        "discount": 10,
        "image1": "bmw_serie1_img1.jpg",
        "image2": "bmw_serie1_img2.jpg",
        "image3": "bmw_serie1_img3.jpg",
        "userId": 0,
        "username": "StanfRei",
        "observedByUsername": "KobyNik",
        "observedByUserId": 3
    },
    {
        "id": 14,
        "brand": "FIAT",
        "model": "500 X Lounge",
        "type": "Berlina",
        "price": 21600,
        "discount": 4,
        "image1": "fiat_500XLounge_img1.jpg",
        "image2": "fiat_500XLounge_img2.jpg",
        "image3": "fiat_500XLounge_img3.jpg",
        "userId": 4,
        "username": "KiaraMur",
        "observedByUsername": "KobyNik",
        "observedByUserId": 3
    },
    {
        "id": 20,
        "brand": "MASERATI",
        "model": "Ghibli",
        "type": "Sportiva",
        "price": 71000,
        "discount": 13,
        "image1": "maserati_ghibli_img1.jpg",
        "image2": "maserati_ghibli_img2.jpg",
        "image3": "maserati_ghibli_img3.jpg",
        "userId": 0,
        "username": "StanfRei",
        "observedByUsername": "KobyNik",
        "observedByUserId": 3
    },
    {
        "id": 3,
        "brand": "FERRARI",
        "model": "Portofino",
        "type": "Sportiva",
        "price": 195000,
        "discount": 14,
        "image1": "ferrari_portofino_img1.jpg",
        "image2": "ferrari_portofino_img2.jpg",
        "image3": "ferrari_portofino_img3.jpg",
        "userId": 2,
        "username": "AmparLed",
        "observedByUsername": "KobyNik",
        "observedByUserId": 3
    },
    {
        "id": 3,
        "brand": "FERRARI",
        "model": "Portofino",
        "type": "Sportiva",
        "price": 195000,
        "discount": 14,
        "image1": "ferrari_portofino_img1.jpg",
        "image2": "ferrari_portofino_img2.jpg",
        "image3": "ferrari_portofino_img3.jpg",
        "userId": 2,
        "username": "AmparLed",
        "observedByUsername": "KobyNik",
        "observedByUserId": 3
    },
    {
        "id": 14,
        "brand": "FIAT",
        "model": "500 X Lounge",
        "type": "Berlina",
        "price": 21600,
        "discount": 4,
        "image1": "fiat_500XLounge_img1.jpg",
        "image2": "fiat_500XLounge_img2.jpg",
        "image3": "fiat_500XLounge_img3.jpg",
        "userId": 4,
        "username": "KiaraMur",
        "observedByUsername": "KiaraMur",
        "observedByUserId": 4
    },
    {
        "id": 2,
        "brand": "FERRARI",
        "model": "F40",
        "type": "Sportiva",
        "price": 900000,
        "discount": 13,
        "image1": "ferrari_f40_img1.jpg",
        "image2": "ferrari_f40_img2.jpg",
        "image3": "ferrari_f40_img3.jpg",
        "userId": 1,
        "username": "JoeVan",
        "observedByUsername": "KiaraMur",
        "observedByUserId": 4
    },
    {
        "id": 21,
        "brand": "MASERATI",
        "model": "MC 20",
        "type": "Sportiva",
        "price": 200000,
        "discount": 13,
        "image1": "maserati_mc20_img1.jpg",
        "image2": "maserati_mc20_img2.jpg",
        "image3": "maserati_mc20_img3.jpg",
        "userId": 3,
        "username": "KobyNik",
        "observedByUsername": "KiaraMur",
        "observedByUserId": 4
    },
    {
        "id": 23,
        "brand": "AUDI",
        "model": "A1",
        "type": "Berlina",
        "price": 22000,
        "discount": 3,
        "image1": "audi_A1_img1.jpg",
        "image2": "audi_A1_img2.jpg",
        "image3": "audi_A1_img3.jpg",
        "userId": 2,
        "username": "AmparLed",
        "observedByUsername": "KiaraMur",
        "observedByUserId": 4
    },
    {
        "id": 0,
        "brand": "MASERATI",
        "model": "Ghibli",
        "type": "Sportiva",
        "price": 71000,
        "discount": 10,
        "image1": "maserati_ghibli_img1.jpg",
        "image2": "maserati_ghibli_img2.jpg",
        "image3": "maserati_ghibli_img3.jpg",
        "userId": 1,
        "username": "JoeVan",
        "observedByUsername": "KiaraMur",
        "observedByUserId": 4
    },
    {
        "id": 26,
        "brand": "BMW",
        "model": "Serie 1",
        "type": "Berlina",
        "price": 27000,
        "discount": 10,
        "image1": "bmw_serie1_img1.jpg",
        "image2": "bmw_serie1_img2.jpg",
        "image3": "bmw_serie1_img3.jpg",
        "userId": 0,
        "username": "StanfRei",
        "observedByUsername": "KiaraMur",
        "observedByUserId": 4
    }
]